version: '3.1'
services:
  postgresql:
    image: postgres:9.6
    volumes:
    - ./conf/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    environment:
      POSTGRES_DB: urbanmedia
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
